{% set version = "0.5.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-formatters
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/formatters_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/formatters/formatters_{{ version }}.tar.gz
  sha256: 8726f0e70a7ecbe01067616ac6eea09065175e62a05b25dcd039c5740a5a7d1d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-htmltools >=0.5.3
    - r-lifecycle >=0.2.0
    - r-stringi >=1.7.12
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-htmltools >=0.5.3
    - r-lifecycle >=0.2.0
    - r-stringi >=1.7.12

test:
  commands:
    - $R -e "library('formatters')"           # [not win]
    - "\"%R%\" -e \"library('formatters')\""  # [win]

about:
  home: https://github.com/insightsengineering/formatters
  license: Apache-2.0
  summary: We provide a framework for rendering complex tables to ASCII, and a set of formatters for transforming values or sets of values into ASCII-ready display strings.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
