{% set version = "0.5.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-formatters
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/formatters_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/formatters/formatters_{{ version }}.tar.gz
  sha256: aff456bae2dca23bcb5e926c585e2d332f75d85f81267a000015289a242408d7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-htmltools
  run:
    - r-base
    - r-checkmate
    - r-htmltools

test:
  commands:
    - $R -e "library('formatters')"           # [not win]
    - "\"%R%\" -e \"library('formatters')\""  # [win]

about:
  home: https://github.com/insightsengineering/formatters
  license: Apache-2.0
  summary: We provide a framework for rendering complex tables to ASCII, and a set of formatters for transforming values or sets of values into ASCII-ready display strings.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
